# CI pipeline for Demo Spring boot service

# Builds and save docker image of demo microservice

variables:
  tag: $(Build.BuildId)
  base: k8s-demo
  artifact-name: k8s-demo-app
  servicename: K8s Demo Service

trigger:
  branches:
    include:
    - qa
    - master
  paths:
    include:
    - $(base)/*
    exclude:
    - $(base)/README.md

stages:
- stage: Build
  displayName: Build and Tests
  jobs:
  - job: Build
    displayName: Build Docker Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: Maven@3
      displayName: Build Docker image
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'spring-boot:build-image'
        publishJUnitResults: false
        jdkVersionOption: '1.11'
        options: '-Dspring-boot.build-image.imageName=objex/k8s-demo-app'
        
    - task: Docker@2
      displayName: Push Docker image
      inputs:
        containerRegistry: 'lmescontainerregistry'
        repository: 'objex/k8s-demo-app'
        command: 'push'
        tags: 'latest'
    - task: CmdLine@2
      displayName: Docker image save
      inputs:
        script: 'docker image save objex/k8s-demo-app:latest -o $(Build.ArtifactStagingDirectory)/microservice.tar'
        
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/*'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'