# CI pipeline for Demo Spring boot service
# Builds and save docker image of demo microservice

variables:
  tag: $(Build.BuildId)
  base: k8s-demo
  artifact-name: k8s-demo-v01
  servicename: K8s Demo Service

trigger:
  branches:
    include:
    - qa
    - master
  paths:
    include:
    - $(base)/*
    exclude:
    - $(base)/README.md

stages:
- stage: Build
  displayName: Build and Tests
  jobs:
  - job: Build
    displayName: Build artifact
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: Maven@3
      displayName: Build Docker image
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'spring-boot:build-image'
        publishJUnitResults: false
        jdkVersionOption: '1.11'

    - task: Docker@2
      displayName: Push Docker image
      inputs:
        containerRegistry: 'lmescontainerregistry'
        repository: 'k8s-demo-app'
        command: 'push'
        tags: '0.0.1-SNAPSHOT'

    - publish:  $(Build.ArtifactStagingDirectory)
      artifact: docker-images
    
